### ISSUE TITLE
desktop notifications - terms and conditions

### ISSUE THREAD

**Issue by cyancey76** [mxew/autodub#12]
ADD:
click the notification to agree to terms and conditions

note: this is a ned request.

**Comment by cyancey76** [comment]
I don't think this should be an autodub notification thing.  This should probably be an eve command that people have to do something to agree other than clicking a popup with no explanation.  Possibly eve can put a short random word you have to type to agree, kind of like a captcha. but still easier to do than to type out/copy "i agree to the terms and conditions"

**Comment by cyancey76** [comment]
@noumenon suggests an option for the initiator to define the join word.

**Comment by mxew** [comment]
Seems this is an idbot request, and not an autodub request. Closing.
