### ISSUE TITLE
desktop notifications - duck killer

### ISSUE THREAD

**Issue by cyancey76** [mxew/autodub#14]
ADD:
add the duck killer name and picture to duck notifications

**Comment by cyancey76** [comment]
Now ned wants it to say something like "17.41251 oz duck was taken down!!!" and chris wants it to say who felled it, which it already does so I guess I'll look at changing it.

Chris also wants to be able to click and send message "NICE SHOT!".

"hey hey @CJY can we get the verbage on the notification to reference the weight of said duck" - ned
"also who felled the duck" - chris
"and clicking on it sends a "@username NICE SHOT!!!"" - chris

**Comment by ghost** [comment]
I wouldn't do the click to send a message. It lets people not come to the room to interact—we want people in the room. My 2¢.

**Comment by cyancey76** [comment]
I suppose we could make it send the message but then ban the sender too.  Then there is incentive not to do things the easy way... 😆 

But then also I guess that takes people out of the room which is the opposite of your point... 😆
