### ISSUE TITLE
Song browser notifications

### ISSUE THREAD

**Issue by cyancey76** [mxew/autodub#25]
We should add a feature to do browser notifications each time a song starts playing, just like a music player app.

**Comment by cyancey76** [comment]
Also, I can't remember how to add labels on Github.

**Comment by ghost** [comment]
> Also, I can't remember how to add labels on Github.

Matt needs to, I believe. https://help.github.com/en/articles/applying-labels-to-issues-and-pull-requests

**Comment by cyancey76** [comment]
Thanks.
