### ISSUE TITLE
Button to hide discoball.

### ISSUE THREAD

**Issue by cyancey76** [mxew/autodub#3]
Button to hide discoball.

**Comment by mxew** [comment]
@cyancey76 A button that hides the discoball temporarily when it is already deployed? Or are you asking for an option to turn the discoball and dancers off entirely? Both?

**Comment by mxew** [comment]
If I remember correctly, the way it worked on turntable back in IDE was that when you clicked the discoball it went back up into the ceiling. We could do something like that.

**Comment by mxew** [comment]
Added in #11
