### ISSUE TITLE
chrome extension sometimes doesn't load on refresh

### ISSUE THREAD

**Issue by mxew** [mxew/autodub#9]

**Comment by rstuckless** [comment]
ok

**Comment by rstuckless** [comment]
ok again

**Comment by mxew** [comment]
an update on this:
seems that when this happens, the autoDub object does exist and the dubtrack api event callbacks appear to be working, but the init function doesn't appear to be firing (which is extra weird because that init function is where we bind the dubtrack api event callbacks)

**Comment by mxew** [comment]
i THINK i fixed this. feel free to open this back up if i'm wrong.
